---

- hosts: "{{ target_host_name | default('all', true) }}"
  # Disable facts as ansible user is not there yet (will fail)
  gather_facts: false
  become: true
  become_user: root
  become_method: sudo
  vars_prompt:
    - name: root_ssh_user
      prompt: SSH user
      default: ubuntu
      unsafe: false
      private: false
    - name: root_ssh_password
      prompt: SSH Password
      unsafe: true
      private: true
    - name: target_host_name
      prompt: Target inventory host name
      unsafe: false
      private: false
  pre_tasks:
    - name: Include users overrides
      include_vars:
        file: users_vars.yml
        name: users_vars
  roles:
    - role: init
      ansible_user: "{{ root_ssh_user }}"
      ansible_password: "{{ root_ssh_password | default(omit, true) }}"
      # Disable ssh key as they will be configured later
      ansible_ssh_private_key_file: null
      tags: init
      vars:
        ## It's mandatory to use hostvars as variable are overridden above
        local_private_key_filepath: "{{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}"
        local_public_key_filepath: "{{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}.pub"
        expected_ansible_user_name: "{{ hostvars[inventory_hostname].ansible_user }}"
        admin_user_name: "{{ users_vars.admin_user_name }}"
        admin_user_shell: "{{ users_vars.admin_user_shell | default(omit) }}"
        admin_user_groups: "{{ users_vars.admin_user_groups | default(omit) }}"
        expected_ansible_user_shell: "{{ users_vars.ansible_user_shell | default(omit) }}"
        expected_ansible_user_groups: "{{ users_vars.ansible_user_groups | default(omit) }}"
        expected_ansible_user_authorized_key_options: "{{ users_vars.ansible_user_authorized_key_options | default(omit) }}"
