---

- name: Check if SSH private key exists
  delegate_to: localhost
  become: false
  changed_when: false
  stat:
    path: "{{ local_private_key_filepath }}"
  register: private_ssh_keys_step

- name: Check if SSH public key exists
  delegate_to: localhost
  changed_when: false
  become: false
  stat:
    path: "{{ local_public_key_filepath }}"
  register: public_ssh_keys_step

## Generate both public and private keys if at least one is missing
- name: Generate SSH public and private keys in case at least one is missing
  import_role:
    name: ssh_keys
    tasks_from: generate-and-fetch-ssh_keys
  tags: manage-local-ssh_keys
  when: not private_ssh_keys_step.stat.exists or not public_ssh_keys_step.stat.exists
