---
argument_specs:
  create:
    options:
      username:
        required: true
        description: "Username for the user to create"
      shell:
        description: "Shell for the user to create. Default to '/bin/bash'"
        default: "/bin/bash"
      user_groups:
        description: "List of group to attache to new user. Default to empty list"
        type: list
        elements: str
        default: []
      sudoers:
        type: bool
        description: "Should user be able to use sudo ? Default false"
        default: false
      sudo_without_pass:
        type: bool
        description: "Should user be able to use sudo without password ? REQUIRES sudoers=true ! Default false"
        default: false
      user_password_file:
        type: str
        description: "Local path (from playbook) where to read/store password for the user"
        default: "{{ username }}_at_{{ inventory_hostname }}.pass"
  configure-ssh-keys-and-connection:
    options:
      username:
        required: true
        description: "Username for the user to create"
      local_private_key_filepath:
        required: true
        type: str
        description: "Local path to the SSH private key"
      local_public_key_filepath:
        required: true
        type: str
        description: "Local path to the SSH public key"
      key_options:
        type: str
        description: "Key options to prepend on remote authorized_keys file for the user"
        default: null # Set null by default, so nothing will be prepended
  ensure-ssh-with-key-works:
    options:
      ssh_user:
        required: true
        type: str
      ssh_host:
        required: true
        type: str
      ssh_key_filepath:
        required: true
        type: str
        description: "Local path to the SSH private key"
  ensure-ssh-with-password-works:
    options:
      ssh_user:
        required: true
        type: str
      ssh_host:
        required: true
        type: str
  create-user-dummy-pass-file-if-needed:
    options:
      user_password_file:
        required: true
        type: str
        description: "Local path (from playbook) where to read/store password for the user"
      username:
        required: true
        description: "Remote username"
  remove-or-restrict-user-pass-file:
    options:
      user_password_file:
        required: true
        type: str
        description: "Local path (from playbook) where to read/store password for the user"
      username:
        required: true
        description: "Remote username"
