---

- block:
    # Flush handlers so ssh server will be restarted if needed (before the next step test ssh connection)
    - name: Flush handlers
      meta: flush_handlers
    - name: "Ensure ssh connection with password works for {{ ssh_user }} user"
      become: false
      delegate_to: localhost
      changed_when: false
      shell:
        cmd: |
          ssh {{ ssh_user }}@{{ ssh_host }} \
            -o "NumberOfPasswordPrompts=2" \
            -o "PreferredAuthentications=password" \
            -o "PasswordAuthentication=yes"\
            -o "PubkeyAuthentication=no" \
            -o "ConnectionAttempts=1" \
            -o "ConnectTimeout=5"
        executable: /bin/bash
      register: ensure_ssh_with_password_step
  rescue:
    - fail:
        msg: "{{ ssh_user }} can't connect to {{ inventory_hostname }} with password !\n{{ ensure_ssh_with_password_step.stderr }}"

